# Generated by Django 2.1.7 on 2019-02-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padelAPI', '0002_auto_20190222_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='court',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
