# Generated by Django 2.1.7 on 2019-02-22 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('padelAPI', '0003_auto_20190222_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Hora Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Hora Fin')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padelAPI.Court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
